---
# tasks file for roles/nsx/add_transport_node_profile
- name: Add transport node profile
  vmware.ansible_for_nsxt.:
    hostname: "{{ nested_nsx.address.ipv4 }}"
    username: "{{ nested_nsx.property.cli_username }}"
    password: "{{ nested_nsx.property.cli_password }}"
    validate_certs: "{{ nested_nsx.validate_certs }}"
    license_key: "{{ common.license.nsxt }}"

