---
# tasks file for roles/vsphere/enable_ntp
- name: Set NTP server at nested esxi cluster
  community.vmware.vmware_host_ntp:
    hostname: "{{ nested_vcsa.fqdn }}"
    username: "{{ common.vsphere.user }}"
    password: "{{ common.vsphere.password }}"
    validate_certs: "{{ common.vsphere.validate_certs }}"
    cluster_name: "{{ nested_vcsa.cluster }}"
    ntp_servers:
      - "{{ common.ntp.primary.ipv4 }}"
      - "{{ common.ntp.secondary.ipv4 }}"
    state: "present"

- name: Start ntpd service at nested esxi cluster
  community.vmware.vmware_host_service_manager:
    hostname: "{{ nested_vcsa.fqdn }}"
    username: "{{ common.vsphere.user }}"
    password: "{{ common.vsphere.password }}"
    validate_certs: "{{ common.vsphere.validate_certs }}"
    cluster_name: "{{ nested_vcsa.cluster }}"
    service_name: "ntpd"
    service_policy: "on"
    state: "start"
