---
esxi_version: "7.x" # 6.x|7.x
build:
  temp_folder: "/tmp/isos"
  mount_point: "/mnt/iso"
  iso_directory: "/home/ichisuke/vmware/iso"
  template_file: "esxi_kickstart.j2"
  esxi_installer: "ESXi-Installer-{{ esxi_version }}"
  # iso_file: "VMware-VMvisor-Installer-6.7.0.update03-14320388.x86_64.iso"
  iso_file: "VMware-VMvisor-Installer-7.0U3f-20036589.x86_64.iso"
  # below vcsa
  ovf_directory: "/home/ichisuke/vmware/ovf"
  vcsa_ova: "VMware-vCenter-Server-Appliance-7.0.3.00800-20150588_OVF10.ova"
  vcsa_iso: "VMware-VCSA-all-7.0.3-20150588.iso"

nested_esxi:
  host:
    esxi11:
      cluster: "nested_cluster_a"
      vm_name: "esxi11"
      fqdn: "esxi11.ichisuke.home"
      guest_id: "vmkernel7Guest" # Enum: GuestOsIdentifier ref: https://developer.vmware.com/apis/1311/vsphere
      vmk:
        vmk0:
          vlan: "0"
          address:
            ipv4:
              address: "192.168.3.221"
              prefix: "24"
              gateway: "192.168.3.1"
      enable_ssh: true
      datastore:
        cache:
          name: "datastore.esxi01.nvme"
          size: 20
        capacity:
          name: "datastore.esxi01.sata"
          size: 80

    esxi12:
      cluster: "nested_cluster_a"
      vm_name: "esxi12"
      fqdn: "esxi12.ichisuke.home"
      guest_id: "vmkernel7Guest" # Enum: GuestOsIdentifier ref: https://developer.vmware.com/apis/1311/vsphere
      vmk:
        vmk0:
          vlan: "0"
          address:
            ipv4:
              address: "192.168.3.222"
              prefix: "24"
              gateway: "192.168.3.1"
      enable_ssh: true
      datastore:
        cache:
          name: "datastore.esxi02.nvme"
          size: 20
        capacity:
          name: "datastore.esxi02.sata"
          size: 80

    esxi13:
      cluster: "nested_cluster_a"
      vm_name: "esxi13"
      fqdn: "esxi13.ichisuke.home"
      guest_id: "vmkernel7Guest" # Enum: GuestOsIdentifier ref: https://developer.vmware.com/apis/1311/vsphere
      vmk:
        vmk0:
          vlan: "0"
          address:
            ipv4:
              address: "192.168.3.223"
              prefix: "24"
              gateway: "192.168.3.1"
      enable_ssh: true
      datastore:
        cache:
          name: "datastore.esxi03.nvme"
          size: 20
        capacity:
          name: "datastore.esxi03.sata"
          size: 80

  hardware_properties:
    nested_cluster_a:
      cpu: 2
      memory: 16384
      boot_size: 32
      vsan:
        cache_size: 20
        capacity_size: 80

  common:
    username: "root"
    password: "VMware1!"
    validate_certs: false
    disk_provisioning: "thin"
    datastore: "datastore.nas01"
    folder: "/nested_vms/"
    iscsi:
      vmhba_name: "vmhba65"
      target_address: "192.168.3.200"


  network:
    dvs:
      storage:
        name: "nested_storage"
        version: "7.0.3"
        mtu: 9000
        num_uplinks: 2
        discovery_protocol: "lldp"
        discovery_operation: "both"
        port_group:
          name: "pg_nested_storage"
          state: "present"
          vlan_id: "0-4094"
          num_ports: 8

nested_vcsa:
  name: "nested_vcsa"
  datastore: "datastore.nas01"
  datacenter: "nested_dc"
  cluster: "nested_cluster_a"
  disk_provi: "thin"
  deploy_size: "tiny"
  folder: "/nested_vms/"
  fqdn: "nested-vcsa.ichisuke.home"
  address:
    ipv4: "192.168.3.220"
    prefix: "24"
    gateway: "192.168.3.1"


common:
  vsphere:
    fqdn: "vcenter01.ichisuke.home"
    user: "administrator@ichisuke.home"
    password: "VMware1!"
    validate_certs: false
    datacenter: "HomeLabDC"
    datastore: "datastore.nas01"
    datastore_path: "ISOs"
    dvs:
      name: "management"
    cluster:
      parent:
        name: "HomeLabCluster"
    port_group:
      nested:
        - name: "nested_mgmt"
          state: "present"
          vlan_id: "0-4094"
          num_ports: 16
          type: "vmxnet3"
        - name: "nested_storage"
          state: "present"
          vlan_id: "0-4094"
          num_ports: 8
          type: "vmxnet3"
  esxi:
    password: "VMware1!"
  dns:
    primary:
      ipv4: "192.168.3.214"
    secondary:
      ipv4: "192.168.3.215"
  ntp:
    primary:
      ipv4: "192.168.3.214"
    secondary:
      ipv4: "192.168.3.215"
  syslog:
    ipv4: "192.168.3.195"
    protocol: "udp"
    port: "514"
  license:
    vcsa: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64343032393038346463626663383930363562316334313962323739366336336237623035623535
          3538393136653637633363356663393764363163643438650a613430396562323533396164396131
          65656432306363646139336531613838393230396234663865656336396262303132633434623131
          6363333232316266360a623034656433636136373263373133636338343536346437383262623963
          30363035326666373863356665333566373836313862643535646330316465653438
    esxi: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32323162353435616432303265613939643638663663336238386437323932346332383263323164
          6139386436643964623539303666653934613234316130350a396637636437356630656538343930
          34383432643539386532616438623439633836316530316161306561326133313365313661303330
          6535633639313634380a393133643164636462623637333636666237626433333239346665386633
          63666135363262363764646131633461363631383735373732333161646363643864

