---
build:
  temp_folder: "/tmp/isos"
  mount_point: "/mnt/isos"
  iso_file: "VMware-VMvisor-Installer-6.7.0.update03-14320388.x86_64.iso"
  iso_directory: "/home/ichisuke/vmware/iso"
  esxi_installer: "ESXi-Installer-6.7.0-update3"
  template_file: "esxi_v6.x_kickstart.j2"

nested_esxi:
  host:
    esxi11:
      cluster: "nested_cluster_a"
      vm_name: "esxi11"
      fqdn: "esxi11.ichisuke.home"
      guest_id: "vmkernel7Guest" # Enum: GuestOsIdentifier ref: https://developer.vmware.com/apis/1311/vsphere
      vmk:
        vmk0:
          vlan: "0"
          address:
            ipv4:
              address: "192.168.3.221"
              prefix: "24"
              gateway: "192.168.3.1"
      enable_ssh: true

    esxi12:
      cluster: "nested_cluster_a"
      vm_name: "esxi12"
      fqdn: "esxi12.ichisuke.home"
      guest_id: "vmkernel7Guest" # Enum: GuestOsIdentifier ref: https://developer.vmware.com/apis/1311/vsphere
      vmk:
        vmk0:
          vlan: "0"
          address:
            ipv4:
              address: "192.168.3.222"
              prefix: "24"
              gateway: "192.168.3.1"
      enable_ssh: true

    esxi13:
      cluster: "nested_cluster_a"
      vm_name: "esxi13"
      fqdn: "esxi13.ichisuke.home"
      guest_id: "vmkernel7Guest" # Enum: GuestOsIdentifier ref: https://developer.vmware.com/apis/1311/vsphere
      vmk:
        vmk0:
          vlan: "0"
          address:
            ipv4:
              address: "192.168.3.223"
              prefix: "24"
              gateway: "192.168.3.1"
      enable_ssh: true

  hardware_properties:
    nested_cluster_a:
      cpu: 4
      memory: 16000
      boot_size: 32
      vsan:
        cache_size: 20
        capacity_size: 100

  common:
    username: "root"
    password: "VMware1!"
    validate_certs: false
    disk_provisioning: "thin"
    datastore: "datastore.nas01"
    folder: "nested_vms"

  network:
    port_group:
      - name: "nested_mgmt"
        type: "vmxnet3"
      - name: "nested_storage"
        type: "vmxnet3"

common:
  vsphere:
    fqdn: "vcenter01.ichisuke.home"
    user: "administrator@ichisuke.home"
    password: "VMware1!"
    validate_certs: false
    datacenter: "HomeLabDC"
    datastore: "datastore.nas01"
    datastore_path: "ISOs"
  esxi:
    password: "VMware1!"
  dns:
    primary:
      ipv4: "192.168.3.214"
    secondary:
      ipv4: "192.168.3.215"
  ntp:
    primary:
      ipv4: "192.168.3.214"
    secondary:
      ipv4: "192.168.3.215"
  syslog:
    ipv4: "192.168.3.195"
    protocol: "udp"
    port: "514"
